### ISSUE TITLE
err message

### ISSUE THREAD

**Issue by okfirelee** [kohler/gifsicle#96]
http://ohwfxc8wt.bkt.clouddn.com/62.gif
gifsicle -O3 --resize-method mix --resize-colors 64 --scale 1 62.gif -o test.gif
err:
get weather api error:gifsicle: warning: too many colors, using local colormaps
  (You may want to try ‘--colors 256’.)

Use this correctly according to tips
gifsicle -O3 --resize-method mix --resize-colors 64 --colors 256 --scale 1

--resize-colors and --colors
These two commands can be used at the same time ? and I don't know how big this number is "--colors"
I want to know the reason why.I want to do is to optimize the image size.

**Comment by saurabheights** [comment]
Gifs can have a local color table(each with 256 colors, and one for each frame) and a global color table. Each gif frame can have at most 256 colors, but if you count all colors the gif has, it can be more than 256. During optimization, one way to reduce size is to remove all the local color tables, and use a single global color table, which is why you are receiving the first warning. Since gifsicle found that there are more than 256 colors, it used local color maps. However further optimization is possible if you inform gifsicle to reduce total colors to at most 256, which will remove all local color tables. 

If you want to reduce size further add --colors 256 at the start, this will remove any local color. Next, resize-colors flag is not going to reduce size but only increase. This flag is used to improve the quality of an image when the number of colors is too low(below 64 in this case) and tells gifsicle to add intermediate colors(gray between black and white) to improve quality. You should read the manual of gifsicle(Run `man gifsicle` on linux/mac).

You should also try [gifsicle-lossy](https://kornel.ski/lossygif) if small reduction(very small) in quality is not an issue. And if possible go for [video conversion](rigor.com/resources/ebooks/the-book-of-gif).
